app/controllers/devices.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template
from flask.json import jsonify
from app.voxity import device, channel
from app.controllers import is_auth
from app.utils import roundup


DEVICES = Blueprint('DEVICES', __name__)


@DEVICES.route('view.html', methods=["GET"])
@is_auth
def devices_view():
    item_per_lst = 4

    devices = device.get(ret_object=True, sort_by_extention=True)
    total_devices = len(devices)
    col = roundup(total_devices / item_per_lst)
    if col >= 4:
        item_per_lst = roundup(total_devices / 3)
        col = 3

    if col == 1:
        container_class = 'container'
    else:
        container_class = 'container-fluid'

    return render_template(
        'devices/index.html',
        container_class=container_class,
        col_length=col,
        item_per_lst=item_per_lst,
        devices=devices
    )


@DEVICES.route('<device_id>.html', methods=["GET"])
@is_auth
def device_view(device_id=None):
    d = device.get_id(device_id, ret_object=True)

    return render_template(
        'devices/id.html',
        container_class='container-fluid',
        device=d,
        calls=channel.get_local_filter(ret_object=True, exten=d.extension)
    )


@DEVICES.route('json/', methods=["GET"])
@is_auth
def devices_json():
    return jsonify({'data': device.get()})


@DEVICES.route('json/<device_id>', methods=["GET"])
@is_auth
def device_json(device_id):
    return jsonify({'data': device.get_id(device_id)})

app/controllers/devices/__init__.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from .views import DEVICES

app/controllers/devices/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, abort
from flask.json import jsonify
from app.voxity import device, channel
from app.controllers import is_auth
from app.utils import roundup


DEVICES = Blueprint('DEVICES',
    __name__,
    template_folder='templates',
    url_prefix='/devices',
    static_folder='static'
)


@DEVICES.route('/index.html', methods=["GET"])
@is_auth
def index():
    item_per_lst = 4
    devices = device.get(ret_object=True, sort_by_extention=True)
    total_devices = len(devices)
    col = roundup(total_devices / item_per_lst)
    if col >= 4:
        item_per_lst = roundup(total_devices / 3)
        col = 3

    if col == 1:
        container_class = 'container'
    else:
        container_class = 'container-fluid'

    return render_template(
        'devices/index.html',
        container_class=container_class,
        col_length=col,
        item_per_lst=item_per_lst,
        devices=devices
    )


@DEVICES.route('/index.json', methods=["GET"])
@is_auth
def devices_json():
    return jsonify({'data': device.get()})


@DEVICES.route('/<device_id>.html', methods=["GET"])
@is_auth
def device_view(device_id=None):
    d = device.get_id(device_id, ret_object=True)

    return render_template(
        'devices/id.html',
        container_class='container-fluid',
        device=d,
        calls=channel.get_local_filter(ret_object=True, exten=d.extension)
    )


@DEVICES.route('/<device_id>.json', methods=["GET"])
@is_auth
def device_json(device_id):

    return jsonify({'data': device.get_id(device_id, ret_object=False)})


@DEVICES.route('/<device_id>/channels.json', methods=["GET"])
def device_channels_json(device_id):
    d = device.get_id(device_id, ret_object=True)
    if d:
        return jsonify({'data': channel.get_local_filter(ret_object=False, exten=d.extension)})
    else:
        abort(404)

app/controllers/devices/templates/devices/id.html
{% extends "layout.html" %}
{% block body %}

<div class="col-xs-12 col-md-6">
    <h2> Informations</h2>
    <hr>
    <div class="panel panel-info">
        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
                <i class="{{device.icon_class}} fa-fw"></i> &nbsp; {{device.extension}}
            </h4>
        </div>
        <div>
            <div class="panel-body">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>Id</td>
                        <td>{{device.id}}</td>
                    </tr>
                    <tr>
                        <td>State</td>
                        <td>{{device.state_desc}}</td>
                    </tr>
                    <tr>
                        <td>Last update</td>
                        <td>{{device.last_update}}</td>
                    </tr>
                    <tr>
                        <td>User Agent</td>
                        <td>{{device.useragent}}</td>
                    </tr>
                    <tr>
                        <td>Enregistrement SIP</td>
                        <td>
                            {% if device.ipaddr %}
                                {{device.ipaddr}}:{{device.port}} ({{device.lastms}}ms)
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
               
            </div>
        </div>
    </div>

</div>

<div class="col-xs-12 col-md-6">
    <h2>Appel en cours <span class="label label-primary pull-right">{{calls|length}}</span></h2>
    <hr>
    
    <ul class="list-group">
    {% for c in calls %}
            {%if c.is_incomming_call() %}
                {% set fa_class='fa-arrow-down'%}
                {% set direction_class='list-group-item-warning'%}
                {% set name=c.caller_name%}
                {% set num=c.caller_num%}
            {% else %}
                {% set fa_class='fa-arrow-up'%}
                {% set direction_class='list-group-item-info'%}
                {% set name=c.callee_num or c.caller_name%}
                {% set num=c.caller_num%}
            {% endif %}
            <li class="list-group-item {{direction_class}}" id="call-{{c.id}}">
                {% if c.get_icon_stat()%}<i class="{{c.get_icon_stat()}}"></i>{% endif %} &nbsp;
                <span data-whois-num="{{num}}" data-whois-suf="  -  "></span> {{num | num_clear_format(space=True)}}
                {%if name | num_clear_format(space=False) != num | num_clear_format(space=False)%}
                    <small> < {{name}} ></small>
                {%endif%}
                <span class="pull-right">
                    <sub><i class="fa fa-phone"></i></sub><sup><i class="fa {{fa_class}}"></i></sup>
                </span>
            </li>
    {% endfor %}
    </ul>

</div>
{% endblock %}

{%block css %}
    <link rel="stylesheet" href="{{url_for('static', filename='res/animate.css/animate.min.css')}}">
{%endblock%}

app/controllers/devices/templates/devices/index.html
{% extends "layout.html" %}
{% block csss %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jqc-1.12.3/dt-1.10.12/r-2.1.0/datatables.min.css"/>
{%endblock%}
{% block body %}
{% set middle_visible = (devices|length / 2)| round(0,'ceil') | int%}

<div class="col-xs-12 text-right">

    <div class="row">
        <div class="col-xs-12 text-right col-offset-sm-2 col-sm-10">
            <div class="btn-group">
                <button type="button" class="btn btn-default" id="show-contact" data-toggle="tooltip" title="Contacts">
                    <i class="fa fa-users"></i>
                </button>
                <button type="button" class="btn btn-default" id="show-channels" data-toggle="tooltip" title="Appels en cours">
                    <i class="fa fa-volume-control-phone"></i>
                </button>
                <button type="button" class="btn btn-default active" id="channels-auto-refresh" data-toggle="tooltip" title="Actualisation automatique">
                    <i class="fa fa-check-square-o"></i>
                </button>
            </div>
        </div>
    </div>
<hr>
</div>
<div class="col-xs-12 {%if col_length > 1%}col-sm-6{%endif%} {%if col_length > 2%}col-md-4{%endif%}">
    <ul class="list-group vox-blf-dashbord">
    {% for d in devices%}
        {% set view_md_start = 1 * item_per_lst%}
        {% set view_md_end = view_md_start + item_per_lst%}
        <li id="{{d.id}}" class="list-group-item  {%if session['user']['internalExtension'] == d.extension%}list-group-item-info{%endif%} visible-xs
            {% if loop.index <= middle_visible%}visible-sm{%endif%}
            {% if loop.index <= view_md_start and loop.index <= view_md_end %}visible-md visible-lg{%endif%}
        ">
            <div class="row">
                <div class="col-xs-2 icon-blf-state">
                    <i class="{{d.icon_class}}" data-toggle="tooltip" title="{{d.state_description}}"></i>
                </div>
                <div class="col-xs-8 {%if d.id%}callable {%endif%}blf-name" data-number="{{d.extension}}">
                    <button role="button" class="btn btn-link btn-block text-left" {%if not d.id%}disabled{%endif%}>{{d.extension}} - {{d.name}}</button>
                </div>
                <div class="col-xs-2 blf-info text-right">
                    {%if d.id %}
                    <a href="{{url_for('DEVICES.device_view', **{'device_id':d.id})}}" role="button" class="btn btn-link pull-right"><i class="fa fa-chevron-right"></i></a>
                    {% endif %}
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
</div>

{%if col_length > 1%}
<div class="col-xs-12 col-sm-6 {%if col_length > 2%}col-md-4{%endif%} hidden-xs">
    <ul class="list-group vox-blf-dashbord">
    {% for d in devices%}
        {% set view_md_start = 1 * item_per_lst%}
        {% set view_md_end = view_md_start + item_per_lst%}
        <li id="{{d.id}}" class="list-group-item  {%if session['user']['internalExtension'] == d.extension%}list-group-item-info{%endif%} 
            {% if loop.index > middle_visible%}visible-sm {%else%} hidden {%endif%} 
            {% if loop.index > view_md_start and loop.index <= view_md_end %}visible-md visible-lg{%endif%}
        ">
            <div class="row">
                <div class="col-xs-2 icon-blf-state">
                    <i class="{{d.icon_class}}" data-toggle="tooltip" title="{{d.state_description}}"></i>
                </div>
                <div class="col-xs-8 {%if d.id%}callable {%endif%}blf-name" data-number="{{d.extension}}">
                    <button role="button" class="btn btn-link btn-block text-left" {%if not d.id%}disabled{%endif%}>{{d.extension}} - {{d.name}}</button>
                </div>
                <div class="col-xs-2 blf-info text-right">
                    {%if d.id %}
                    <a href="{{url_for('DEVICES.device_view', **{'device_id':d.id})}}" role="button" class="btn btn-link pull-right"><i class="fa fa-chevron-right"></i></a>
                    {% endif %}
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
</div>
{%endif%}

{%if col_length > 2%}
<div class="col-xs-12 col-sm-6 col-md-4 visible-md visible-lg">
    <ul class="list-group vox-blf-dashbord">
    {% for d in devices%}
        {% set view_md_start = 2 * item_per_lst%}
        {% set view_md_end = view_md_start + item_per_lst%}
        <li id="{{d.id}}" class="list-group-item  {%if session['user']['internalExtension'] == d.extension%}list-group-item-info{%endif%} 
            {% if loop.index > view_md_start and loop.index <= view_md_end%}visible-sm visible-md visible-lg {%else%} hidden {%endif%}
            
        ">
            <div class="row">
                <div class="col-xs-2 icon-blf-state">
                    <i class="{{d.icon_class}}" data-toggle="tooltip" title="{{d.state_description}}"></i>
                </div>
                <div class="col-xs-8 {%if d.id%}callable {%endif%}blf-name" data-number="{{d.extension}}">
                    <button role="button" class="btn btn-link btn-block text-left" {%if not d.id%}disabled{%endif%}>{{d.extension}} - {{d.name}}</button>
                </div>
                <div class="col-xs-2 blf-info text-right">
                    {%if d.id %}
                    <a href="{{url_for('DEVICES.device_view', **{'device_id':d.id})}}" role="button" class="btn btn-link pull-right"><i class="fa fa-chevron-right"></i></a>
                    {% endif %}
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
</div>
{%endif%}

<!-- Modal -->
<div class="modal fade" id="main-modal" tabindex="-1" role="dialog" aria-labelledby="mm-head" data-view="">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="mm-head">Modal title</h4>
            </div>
            <div class="modal-body" style="padding:1àpx;">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-toggle="tooltip" title="Actualiser" id="mm-refresh"><i class="fa fa-refresh"></i></button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{url_for('static', filename='res/animate.css/animate.min.css')}}">
{% endblock %}

{% block jsscript %} 
    <script>
        {%if devices|length%}
        var STATES_TRANSLATE ={ {%for lg in devices[0]._DESCRIPTION.keys() %}
            '{{lg}}':{ 
                {%for k in devices[0]._DESCRIPTION[lg].keys() %}'{{k}}': "{{devices[0]._DESCRIPTION[lg][k]}}",{%endfor%}
            },{%endfor%}
        {%endif%}
        }
    </script>
    <script src="{{url_for('DEVICES.static', filename='js/devices.js')}}"></script>
    <script src="{{url_for('static', filename='js/dashboard.js')}}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.js"></script>

{% endblock %}