app/controllers/calls_log.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, request, session, abort
from flask.json import jsonify
from app.voxity.channel import get_log
from app.controllers import is_auth
from app.utils import value_or_zero


CALLS_LOG = Blueprint('CALLS_LOG', __name__)

LIST_AVAILABLE = [5, 10, 25, 50, 100]


@CALLS_LOG.route('all.json', methods=["GET"])
@is_auth
def json_data():
    return jsonify({'data': get_log()})


@CALLS_LOG.route('my.json', methods=["GET"])
@is_auth
def my_json():
    return jsonify(
        {'data': get_log(
            dstchannel=session['user']['internalExtension']
        )}
    )


@CALLS_LOG.route('<direction>_calls.html', methods=["GET"])
@is_auth
def view(direction='incoming'):
    if direction not in ['incoming', 'outing']:
        abort(404)

    item = request.args.get('item', 25)
    page = request.args.get('page', 1)
    pager = dict()
    params = dict()

    if item != 'all':
        params['page'] = page
        params['limit'] = item

    if direction == "outing":
        params['src_phonenumber'] = session['user']['internalExtension']
    else:
        params['dstchannel'] = '*-{0}-*'.format(
            session['user']['internalExtension']
        )

    log = get_log(**params)

    try:
        if item != "all":
            item = int(item)
            pager['current'] = int(value_or_zero(log['pager']['curent']))
            pager['max'] = int(value_or_zero(log['pager']['max_page']))
            pager['min'] = 1
            pager['start'] = 1
            pager['end'] = pager['max']

            if pager['end'] - pager['start'] > 10:
                pager['start'] = pager['current'] - 5
                if pager['start'] < 1:
                    pager['start'] = 1

                pager['end'] = pager['start'] + 10
                if pager['end'] > pager['max']:
                    pager['end'] = pager['max']
                    pager['start'] = pager['end'] - 10

    except Exception as e:
        raise e

    return render_template(
        'calls_log/index.html',
        log=log['list'] or [],
        pager=pager,
        item=item,
        items=LIST_AVAILABLE,
        log_total=int(value_or_zero(log['pager']['total_item'])),
    ).encode('utf-8')


@CALLS_LOG.route('<direction>_calls.json', methods=["GET"])
@is_auth
def json_view(direction='incoming'):
    if direction not in ['incoming', 'outing']:
        abort(404)

    item = request.args.get('item', 25)
    page = request.args.get('page', 1)
    pager = dict()
    params = dict()

    if item != 'all':
        params['page'] = page
        params['limit'] = item

    if direction == "outing":
        params['src_phonenumber'] = session['user']['internalExtension']
    else:
        params['dstchannel'] = '*-{0}-*'.format(
            session['user']['internalExtension']
        )

    log = get_log(**params)

    try:
        item = int(item)
        pager['current'] = int(value_or_zero(log['pager']['curent']))
        pager['max'] = int(value_or_zero(log['pager']['max_page']))
        pager['min'] = 1
        pager['start'] = 1
        pager['end'] = pager['max']

        if pager['end'] - pager['start'] > 10:
            pager['start'] = pager['current'] - 5
            if pager['start'] < 1:
                pager['start'] = 1

            pager['end'] = pager['start'] + 10
            if pager['end'] > pager['max']:
                pager['end'] = pager['max']
                pager['start'] = pager['end'] - 10

    except Exception, e:
        raise e
        abort(500)

    return jsonify(
        {'data': log}
    )

app/controllers/calls_log/__init__.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from .views import CALLS_LOG

app/controllers/calls_log/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, request, session, abort
from flask.json import jsonify
from app.voxity.channel import get_log
from app.controllers import is_auth
from app.utils import value_or_zero


CALLS_LOG = Blueprint('CALLS_LOG',
    __name__,
    template_folder='templates',
    url_prefix='/calls_log'
)

LIST_AVAILABLE = [5, 10, 25, 50, 100]


@CALLS_LOG.route('/all.json', methods=["GET"])
@is_auth
def json_data():
    return jsonify({'data': get_log()})


@CALLS_LOG.route('/my.json', methods=["GET"])
@is_auth
def my_json():
    return jsonify(
        {'data': get_log(
            dstchannel=session['user']['internalExtension']
        )}
    )


@CALLS_LOG.route('/<direction>_calls.html', methods=["GET"])
@is_auth
def view(direction='incoming'):
    if direction not in ['incoming', 'outing']:
        abort(404)

    item = request.args.get('item', 25)
    page = request.args.get('page', 1)
    pager = dict()
    params = dict()

    if item != 'all':
        params['page'] = page
        params['limit'] = item

    if direction == "outing":
        params['src_phonenumber'] = session['user']['internalExtension']
    else:
        params['dstchannel'] = '*-{0}-*'.format(
            session['user']['internalExtension']
        )

    log = get_log(**params)

    try:
        if item != "all":
            item = int(item)
            pager['current'] = int(value_or_zero(log['pager']['curent']))
            pager['max'] = int(value_or_zero(log['pager']['max_page']))
            pager['min'] = 1
            pager['start'] = 1
            pager['end'] = pager['max']

            if pager['end'] - pager['start'] > 10:
                pager['start'] = pager['current'] - 5
                if pager['start'] < 1:
                    pager['start'] = 1

                pager['end'] = pager['start'] + 10
                if pager['end'] > pager['max']:
                    pager['end'] = pager['max']
                    pager['start'] = pager['end'] - 10

    except Exception as e:
        raise e

    return render_template(
        'calls_log/index.html',
        log=log['list'] or [],
        pager=pager,
        item=item,
        items=LIST_AVAILABLE,
        log_total=int(value_or_zero(log['pager']['total_item'])),
    ).encode('utf-8')


@CALLS_LOG.route('/<direction>_calls.json', methods=["GET"])
@is_auth
def json_view(direction='incoming'):
    if direction not in ['incoming', 'outing']:
        abort(404)

    item = request.args.get('item', 25)
    page = request.args.get('page', 1)
    pager = dict()
    params = dict()

    if item != 'all':
        params['page'] = page
        params['limit'] = item

    if direction == "outing":
        params['src_phonenumber'] = session['user']['internalExtension']
    else:
        params['dstchannel'] = '*-{0}-*'.format(
            session['user']['internalExtension']
        )

    log = get_log(**params)

    try:
        item = int(item)
        pager['current'] = int(value_or_zero(log['pager']['curent']))
        pager['max'] = int(value_or_zero(log['pager']['max_page']))
        pager['min'] = 1
        pager['start'] = 1
        pager['end'] = pager['max']

        if pager['end'] - pager['start'] > 10:
            pager['start'] = pager['current'] - 5
            if pager['start'] < 1:
                pager['start'] = 1

            pager['end'] = pager['start'] + 10
            if pager['end'] > pager['max']:
                pager['end'] = pager['max']
                pager['start'] = pager['end'] - 10

    except Exception:
        abort(500)

    return jsonify(
        {'data': log}
    )

app/controllers/calls_log/templates/calls_log/index.html
{% extends "layout.html" %}
{% block body %}
<div class="col-xs-12">
    <ul class="nav nav-tabs nav-justified">
        <li{%if url_for('CALLS_LOG.view', **{'direction':'incoming'}) == request.path%} class="active"{%endif%}>
            <a href="{{url_for('CALLS_LOG.view', **{'direction':'incoming'})+'?item='}}{{item}}"> Incoming Calls</a>
        </li>
        <li{%if url_for('CALLS_LOG.view', **{'direction':'outing'}) == request.path%} class="active"{%endif%}>
            <a href="{{url_for('CALLS_LOG.view', **{'direction':'outing'})+'?item='}}{{item}}"> Outing Calls</a>
        </li>
    </ul>
    {%if url_for('CALLS_LOG.view', **{'direction':'incoming'}) == request.path%}
    <div class="alert alert-danger" role="alert">
        <strong>Error !</strong><br>
        this view is not working. it's not possible to get your incoming call list
    </div>
    {%endif%}
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <th>
                    <div class="dropdown" >
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            {{item}}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            {% for i in items%}
                            <li {% if i == item%} class="active" {%endif%}><a href="?item={{i}}">{{i}}</a></li>
                            {% endfor %}
                            <li role="separator" class="divider"></li>
                            <li {% if item == 'all' %} class="active" {%endif%}><a href="?item=all">All</a></li>
                        </ul>
                    </div>
                </th>
                <th class="text-center">date time</th>
                <th class="text-center">
                {%if url_for('CALLS_LOG.view', **{'direction':'incoming'}) == request.path%}
                    source phone number
                {%else%}
                    Destination call
                {%endif%}
                </th>
                <th class="text-center">duration</th>
            </thead>
            <tbody>
                {% for c in log%}
                <tr>
                    <td colspan="2">
                        {{c['calldate']}}
                    </td>
                    {%if url_for('CALLS_LOG.view', **{'direction':'incoming'}) == request.path%}
                        <td {%if c['source']%}class="callable" data-number="{{c['source']}}"{%endif%}>
                            <span data-whois-num="{{c['source']}}" data-whois-suf="  -  "></span> {{c['source'] | num_clear_format(space=True)}}
                        </td>
                    {%else%}
                        <td {%if c['destination']%}class="callable" data-number="{{c['destination']}}"{%endif%}>
                            <span data-whois-num="{{c['destination']|num_clear_format(space=False)}}" data-whois-suf="  -  "></span>{{c['destination']| num_clear_format(space=True)}}
                        </td>
                    {%endif%}
                    <td>
                        {{c['duration']}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="active">
                    <td>
                        {% if  item != 'all' and pager['max']%}
                            <strong>view</strong> : 
                            {{(pager['current'] * item ) - item + 1}} - 
                            {% if pager['current'] * item < log_total%}
                                {{pager['current'] * item}}
                            {%else%}
                                {{log_total}}
                            {% endif %}

                        {% endif %}
                    </td>
                    <td colspan="2" class="text-right">
                        <strong>Total</strong>
                    </td>
                    <td>
                        {{log_total or 0}}
                    </td>
                </tr>
            </tfoot>
        </table>        
    </div>
    {% if item != 'all' and pager['max']%}
        <nav class="text-center">
            <ul class="pagination">
                <li>
                  <a href="?item={{item}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                {% if pager['min'] < pager['start'] %}
                <li class="disabled"><a >...</a></li>
                {%endif%}
                </li>
                {% for i in range(pager['start'], pager['end'] + 1) %}
                    <li {%if i == pager['current']%}class="active"{%endif%}><a href="?item={{item}}&page={{i}}">{{i}}</a></li>
                {%endfor%}
                {% if pager['max'] > pager['end'] %}
                <li class="disabled"><a >...</a></li>
                {%endif%}
                <li>
                  <a href="?item={{item}}&page={{pager['max']}}">
                    <span aria-hidden="{{true}}">&raquo;</span>
                  </a>
                </li>
            </ul>
        </nav>


    {%endif%}
</div>
{% endblock %}