app/controllers/contacts.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, request, abort, redirect, url_for, session
from flask.json import jsonify
from app.voxity import contact
from app.controllers import is_auth, is_admin
from app.utils import value_or_zero
from app.voxity.objects.contact import ContactForm


CONTACT = Blueprint('CONTACT', __name__)
LIST_AVAILABLE = [5, 10, 25, 50, 100]


@CONTACT.route('all.json', methods=["GET"])
@is_auth
def json_data():
    resp = contact.get().get('list', [])
    for num in contact.Contact.LOCAL_EXTEN.keys():
        resp.append({
            'telephoneNumber': num,
            'cn': contact.Contact.LOCAL_EXTEN[num]
        })
    return jsonify({'data': resp})


@CONTACT.route('', methods=["GET"])
@CONTACT.route('index.html', methods=["GET"])
@is_auth
def view():

    item = request.args.get('item', 25)
    page = request.args.get('page', 1)
    pager = dict()

    if item != 'all':
        contacts = contact.get(page=page, limit=item, ret_object=True)
        contact_total = int(value_or_zero(contacts['pager']['total_item']))

        # try:
        item = int(item)
        pager['current'] = int(value_or_zero(contacts['pager']['curent']))
        pager['max'] = int(value_or_zero(contacts['pager']['max_page']))
        pager['min'] = 1
        pager['start'] = 1
        pager['end'] = pager['max']

        if pager['end'] - pager['start'] > 10:
            pager['start'] = pager['current'] - 5
            if pager['start'] < 1:
                pager['start'] = 1

            pager['end'] = pager['start'] + 10
            if pager['end'] > pager['max']:
                pager['end'] = pager['max']
                pager['start'] = pager['end'] - 10

        # except Exception:
            # contacts = contact.get(ret_object=True)
            # item = 'all'
    else:
        contacts = contact.get(ret_object=True)
        contact_total = contact['pager']
    return render_template(
        'contacts/index.html',
        container_class='container-fluid',
        contacts=contacts['list'],
        pager=pager,
        item=item,
        items=LIST_AVAILABLE,
        contact_total=contact_total,
        search_mode=False,
    ).encode('utf-8')


@CONTACT.route('<uid>.json', methods=["GET"])
@is_auth
def contact_uid(uid=None):
    c = contact.get_uid(uid=uid)
    if c:
        return jsonify({'data': c})
    else:
        abort(404)


@CONTACT.route('search.html', methods=['GET'])
@is_auth
def search():
    c = list()
    form_value = dict()
    if not request.args.get('name', None):
        abort(400)
    else:
        form_value['name'] = "{0}".format(request.args.get('name', ''))

    c = contact.get(cn=form_value['name'], ret_object=True)
    return render_template(
        'contacts/index.html',
        container_class='container-fluid',
        contacts=c['list'],
        item="all",
        contact_total=len(c['list']),
        search_mode=True,
        form_value=form_value
    ).encode('utf-8')


@CONTACT.route('search.json', methods=['GET'])
@is_auth
def search_json():
    search = dict()
    for k in request.args:
        search[k] = request.args[k]

    c = contact.get(**search)
    return jsonify({'data': c})


@CONTACT.route('whois.json', methods=['GET'])
@is_auth
def whois():

    if not request.args.get('number', ''):
        abort(400)

    c = list()
    name_list = list()

    number = '{0}'.format(
        request.args.get('number')
    ).replace(' ', '').replace('.', '').replace('-', '')

    if number in contact.Contact.LOCAL_EXTEN:
        c.append({
            'telephoneNumber': number,
            'cn': contact.Contact.LOCAL_EXTEN[number]
        })
    else:
        c += contact.get()['list']

    for elt in c:
        if elt.get('mobile', '') == number or \
           elt.get('telephoneNumber', '') == number:
            name_list.append(elt)

    return jsonify({'data': name_list})


@CONTACT.route('whois.html', methods=['GET'])
@is_auth
def whois_view():

    if not request.args.get('number', ''):
        abort(400)

    c = list()
    name_list = list()

    number = '{0}'.format(
        request.args.get('number')
    ).replace(' ', '').replace('.', '').replace('-', '')

    if number in contact.Contact.LOCAL_EXTEN:
        c.append(
            contact.Contact(
                uid='local-' + number,
                telephoneNumber=number,
                cn=contact.Contact.LOCAL_EXTEN[number]
            )
        )
    else:
        c += contact.get(ret_object=True)['list']

    for elt in c:
        if elt.mobile == number or \
           elt.telephone_number == number:
            name_list.append(elt)

    if len(name_list) == 1:
        return redirect(url_for('.view_uid', uid=name_list[0].uid))
    else:
        return render_template(
            'contacts/index.html',
            container_class='container-fluid',
            contacts=name_list,
            item="all",
            contact_total=len(name_list),
            whois_mode=True
        ).encode('utf-8')


@CONTACT.route('add.html', methods=['GET'])
@is_auth
@is_admin
def get_add(form=None, api_errors=None):
    validate_state = False
    if form:
        validate_state = True
    return render_template(
        'contacts/form.html',
        form=form or ContactForm(),
        api_errors=api_errors,
        validate_state=validate_state
    ).encode('utf-8')


@CONTACT.route('add.html', methods=['POST'])
@is_auth
@is_admin
def post_add():
    api_errors = None
    form = ContactForm(request.form)
    form.strip_value()
    if form.validate():
        c = form.get_object(contact.Contact)
        resp = contact.add(**c.to_dict(is_query=True))
        if resp.get('status', False) == 200 and resp.get('result', {}).get('uid', False):
            session['new_contact'] = c.to_dict()
            return redirect(url_for('.view'))
        else:
            api_errors = resp.get('error', {'internal': 'Error inconnue'})
            if not isinstance(api_errors, dict):
                api_errors = {'message': api_errors}

    return get_add(form=form, api_errors=api_errors)


@CONTACT.route('local-<num>.html', methods=["GET"])
@is_auth
def view_local(num):
    c = contact.Contact(
        uid='local-' + num,
        telephoneNumber=num,
        cn=contact.Contact.LOCAL_EXTEN[num]
    )

    return render_template(
        'contacts/view.html',
        contact=c,
        read_only=True
    ).encode('utf-8')


@CONTACT.route('<uid>.html', methods=["GET"])
@is_auth
def view_uid(uid):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    return render_template(
        'contacts/view.html',
        contact=c,
    ).encode('utf-8')


@CONTACT.route('edit/<uid>.html', methods=["GET"])
@is_auth
@is_admin
def edit(uid=None):
    c = contact.get_uid(uid=uid, ret_object=True)
    if c:
        c_form = ContactForm(**c.to_dict())
        return render_template(
            'contacts/form.html',
            form=c_form,
            edit_mode=True
        ).encode('utf-8')
    else:
        abort(404)


@CONTACT.route('edit/<uid>.html', methods=["POST"])
@is_auth
@is_admin
def edit_save(uid=None):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    if request.form['uid'] != uid:
        abort(400)

    c_form = ContactForm(request.form)
    c_form.strip_value()
    if c_form.validate():
        c = c_form.get_object(contact.Contact)
        resp = contact.update(**c.to_dict(is_query=True))
        if resp and resp.get('result') and resp.get('result').get('uid', None) == uid and not resp.get('errors') and not resp.get('error'):
            session['update_contact'] = c.to_dict()
            return redirect(url_for('.view'))
        else:
            error = resp.get('error', {})
            if not isinstance(error, dict):
                error = {
                    'message': error
                }
            return render_template(
                'contacts/form.html',
                form=c_form,
                edit_mode=True,
                api_errors=error,
                validate_state=True
            ).encode('utf-8')
    else:
        return render_template(
            'contacts/form.html',
            form=c_form,
            edit_mode=True,
            validate_state=True
        ).encode('utf-8')


@CONTACT.route('remove-<uid>.html', methods=["GET"])
@is_auth
@is_admin
def remove_warning(uid):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    return render_template(
        'contacts/remove.html',
        contact=c
    ).encode('utf-8')


@CONTACT.route('remove-<uid>.html', methods=["POST"])
@is_auth
@is_admin
def remove(uid):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    if request.form['uid'] != uid:
        abort(400)

    if contact.remove(uid):
        session['remove_contact'] = c.to_dict()
        return redirect(url_for('.view'))
    else:
        abort(500)

app/controllers/contacts/__init__.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from .views import CONTACT

app/controllers/sms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, request, session, redirect, url_for
from flask.json import jsonify
from app.voxity import sms
from app.voxity.objects.sms import SmsForm, Sms
from app.controllers import is_auth


SMS = Blueprint('SMS', __name__)


@SMS.route('json/', methods=["GET"])
@is_auth
def sms_json():
    return jsonify({'data': sms.get()})


@SMS.route('json/group_by_dest', methods=["GET"])
@is_auth
def sms_gp_by():
    return jsonify({'data': sms.get_group_by_dest()})


@SMS.route('json/responses', methods=["GET"])
@is_auth
def sms_responses():
    return jsonify({'data': sms.get_responses()})


@SMS.route('', methods=["GET"])
@SMS.route('index.html', methods=["GET"])
@is_auth
def index():
    return render_template(
        'sms/index.html',
        container_class="container-fluid",
        sms=sms.get_group_by_dest(ret_object=True)
    )


@SMS.route('new.html', methods=["GET"])
@is_auth
def new():
    return render_template(
        'sms/form.html',
        form=SmsForm(request.args)
    )


@SMS.route('new.html', methods=["POST"])
@is_auth
def send():
    sms_form = SmsForm(request.form)
    sms_form.strip_value()
    if sms_form.validate():
        save_to_session = {}
        save_to_session['content'] = sms_form.content.data
        save_to_session['phone_numbers'] = sms_form.phone_number.data
        save_to_session['emitter'] = sms_form.emitter.data

        for mess in sms_form.get_object(Sms):
            sms.send(mess)

        session['new_sms_list'] = save_to_session
        return redirect(url_for('.index'))

    else:
        return render_template(
            'sms/form.html',
            form=sms_form,
            validate_state=True,
        )

app/controllers/contacts/templates/contacts/form.html
{% extends "layout.html" %}
{% block body %}
    {%if not edit_mode%}
    <h3>Ajout d'un contact</h3>
    {% else %}
    <h3>Modification de contact <span class="text-muted">-</span> <small>{{form['cn'].data}}</small></h3>
    {%endif%}

    
    <hr>
    {%if api_errors%}
        <div class="alert alert-danger">
            {%for k in api_errors.keys()%}
                <strong>{{k}}</strong> : {{api_errors[k]}}<br>
            {%endfor%}
        </div>
    {%endif%}
    <form action="" method="POST" class="col-xs-12">

        <div class="row">
            <div class="col-xs-12 col-sm-offset-2 col-sm-8">
                {{input_text(form['cn'], errors=form.errors.get('cn', None), addon_icon='fa fa-user', validate=validate_state)}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-xs-12 col-sm-8">
                {{input_text(form['telephone_number'], placeholder="xx xx xx xx xx", errors=form.errors.get('telephone_number', None), addon_icon='fa fa-phone', validate=validate_state)}}
            </div>
            <div class="col-xs-12 col-sm-4">
                {{input_text(form['phone_number_raccourci'], placeholder="*1234", errors=form.errors.get('phone_number_raccourci', None), validate=validate_state)}}
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-xs-12 col-sm-8">
                {{input_text(form['mobile'], placeholder="xx xx xx xx xx", errors=form.errors.get('mobile', None), addon_icon='fa fa-mobile', validate=validate_state)}}
            </div>
            <div class="col-xs-12 col-sm-4">
                {{input_text(form['phone_mobile_raccourci'], placeholder="*1234", errors=form.errors.get('phone_mobile_raccourci', None), validate=validate_state)}}
            </div>
        </div>
        <hr>
        <p>
            {{input_text(form['mail'], errors=form.errors.get('mail', None), addon_icon='fa fa-at', validate=validate_state)}}
        </p>
        <hr>
        {%if not edit_mode%}
        <p class="text-center">
            <button class="btn btn-success">Ajouter <i class="fa fa-plus"></i></button>
        </p>
        {% else %}
            <p class="text-center">
                {{form['uid'](class="hidden")}}
                <button class="btn btn-success">Modifier <i class="fa fa-check"></i></button>
            </p>
        {%endif%}

        
    </form>
{% endblock %}

app/controllers/contacts/templates/contacts/index.html
{% extends "layout.html" %}
{% block body %}
<div class="col-xs-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
    {% if 'new_contact' in session or 'update_contact' in session%}
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span>&times;</button>
        <i class="fa fa-check fa-fw"></i>
        {% if 'new_contact' in session%}
        Contact <strong>{{session['new_contact']['cn']}}</strong> est ajouté.
        <a href="{{url_for('CONTACT.search', name=session['new_contact']['cn'])}}" class="btn btn-xs btn-success pull-right"><i class="fa fa-search"></i></a>
        {%set tmp = session.pop('new_contact')%}
        {%else%}
        Contact <strong>{{session['update_contact']['cn']}}</strong> mis à jour.
        <a href="{{url_for('CONTACT.search', name=session['update_contact']['cn'])}}" class="btn btn-xs btn-success pull-right"><i class="fa fa-search"></i></a>
        {%set tmp = session.pop('update_contact')%}
        {%endif%}
    </div>
    {%endif%}
    {% if 'remove_contact' in session%}
    <div class="alert alert-danger" id="alr-remoce-{{session['remove_contact'].pop('uid', None)}}">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span>&times;</button>
        <i class="fa fa-trash fa-fw"></i> Contact <strong>{{session['remove_contact'].cn}}</strong> supprimé.
        <form action="{{url_for('CONTACT.post_add')}}" method="POST" class="pull-right">
            {%for k in session['remove_contact'].keys()%}
                <input type="hidden" name="{{k}}" value="{{session['remove_contact'][k]}}">
            {%endfor%}
            <button class="btn btn-danger btn-xs" type="submit" data-toggle="tooltip" title="annuler"><i class="fa fa-undo"></i></button>
        </form>
        {%set tmp = session.pop('remove_contact')%}
    </div>
    {%endif%}
    {%if is_admin()%}
    <p class="text-right">
        <a href="{{url_for('CONTACT.get_add')}}" class="btn btn-primary"><i class="fa fa-plus"></i></a>
    </p>
    {%endif%}
    {%if not whois_mode%}
    <p>
        <h4>Recherche</h4>
        <form method="GET" action="{{url_for('CONTACT.search')}}">
          <div class="input-group">
                {% if search_mode%}
                <span class="input-group-btn">
                    <a class="btn btn-default" role="button" href="{{url_for('CONTACT.view')}}" id="contact-back-to-link"><i class="fa fa-times text-danger"></i></a>
                </span>
                {%endif%}
                <input type="text" class="form-control" placeholder="Search for by name" name="name" {%if search_mode%}value="{{form_value['name']}}"{%endif%}>
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
    </p>
    {% endif %}
    <hr>
{%if contacts|length > 0%}
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <th>
                    {% if not search_mode %}
                    <div class="dropdown" >
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            {{item}}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            {% for i in items%}
                            <li {% if i == item%} class="active" {%endif%}><a href="?item={{i}}">{{i}}</a></li>
                            {% endfor %}
                            <li role="separator" class="divider"></li>
                            <li {% if item == 'all' %} class="active" {%endif%}><a href="./">All</a></li>
                        </ul>
                    </div>
                    {% endif %}
                    Nom
                </th>
                <th class="text-center">Numéro principal</th>
                <th class="text-center">Numéro secondaire</th>
                <th class="text-center">Mail</th>
                <th style="min-width:110px; max-width:110px; width:110px">
                    <div class="btn-group btn-group-xs disabled">
                        <button class="btn btn-default btn-xs disabled" data-toggle="tooltip" title="Détail"><i class="fa fa-eye"></i></button>
                        <button class="btn btn-success btn-xs disabled" data-toggle="tooltip" title="Envoyer un SMS"><i class="fa fa-comment-o"></i></button>
                        {%if is_admin()%}
                        <button class="btn btn-info btn-xs disabled" data-toggle="tooltip" title="Modifier"><i class="fa fa-edit"></i></button>
                        <button class="btn btn-danger btn-xs disabled" data-toggle="tooltip" title="Suprimer"><i class="fa fa-trash-o"></i></button>
                        {%endif%}
                    </div>
                </th>
            </thead>
            <tbody>
                {% for c in contacts%}
                <tr>
                    <td>
                        {{c['cn']}}
                    </td>
                    <td {%if c.telephone_number%}class="callable"{%endif%}{% if c.phone_number_raccourci %} title="click2call - {{c.phone_number_raccourci}}"{% endif %}>
                        {{c.telephone_number |num_clear_format}}
                        
                    </td>
                    <td {%if c.mobile%}class="callable"{%endif%} {% if c.phone_mobile_raccourci %} title="click2call - {{c.phone_mobile_raccourci}}"{% endif %}>
                        {{c.mobile |num_clear_format}}
                    </td>
                    <td>
                        {% if c.mail%}
                        <a href="mailto:{{c.mail}}">{{c.mail}}</a>
                        {%endif%}

                    </td>
                    <td class="text-right">
                        <div class="btn-group btn-group-xs">
                            <a href="{{url_for('CONTACT.view_uid', **{'uid':c.uid})}}" class="btn btn-default btn-xs"><i class="fa fa-eye"></i></a>
                            {%if c.have_mobile()%}
                            <a href="{{url_for('SMS.new', phone_number=c.have_mobile()[0])}}" class="btn btn-success btn-xs"><i class="fa fa-comment-o"></i></a>
                            {# {%else%}
                            <button class="btn btn-success btn-xs disabled" disabled><i class="fa fa-comment-o"></i></button>#}
                            {%endif%}
                            {%if is_admin()%}
                            <a href="{{url_for('CONTACT.edit', **{'uid':c.uid})}}" class="btn btn-info btn-xs"><i class="fa fa-edit"></i></a>
                            <a href="{{url_for('CONTACT.remove_warning', **{'uid':c.uid})}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
                            {%endif%}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="active">
                    <td>
                        {% if  item != 'all' %}
                            <strong>Vue</strong> : 
                            {{(pager['current'] * item ) - item + 1}} - 
                            {% if pager['current'] * item < contact_total%}
                                {{pager['current'] * item}}
                            {%else%}
                                {{contact_total}}
                            {% endif %}

                        {% endif %}
                    </td>
                    <td colspan="2"></td>
                    <td colspan="1" class="text-right">
                        <strong>Total</strong>
                    </td>
                    <td>
                        {{contact_total}}
                    </td>
                </tr>
            </tfoot>
        </table>        
    </div>
    {% if item != 'all'%}
        <nav class="text-center">
            <ul class="pagination">
                <li>
                  <a href="?item={{item}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                {% if not pager['min'] < pager['start'] %}
                <li class="disabled"><a >...</a></li>
                {%endif%}
                </li>
                {% for i in range(pager['start'], pager['end'] + 1) %}
                    <li {%if i == pager['current']%}class="active"{%endif%}><a href="?item={{item}}&page={{i}}">{{i}}</a></li>
                {%endfor%}
                {% if pager['max'] > pager['end'] %}
                <li class="disabled"><a >...</a></li>
                {%endif%}
                <li>
                  <a href="?item={{item}}&page={{pager['max']}}">
                    <span aria-hidden="{{true}}">&raquo;</span>
                  </a>
                </li>
            </ul>
        </nav>
    {%endif%}


{% elif  not search_mode and not whois_mode%}
    <p class="alert alert-info text-center">
        Vous n'avez aucun contact renseigné dans l'annuaire 
    </p>
{%elif whois_mode%}
    <p class="alert alert-info text-center">
        Aucun contact trouvez avec un numéro : <strong>{{request.args.get('number')}}</strong>
    </p>
{% endif %}
</div>
{% endblock %}

app/controllers/contacts/templates/contacts/remove.html
{% extends "layout.html" %}
{% block body %}
<div class="col-xs-12">
    <h3 class="text-danger"> <i class="fa fa-exclamation-triangle fa-fw"></i> Suppresion de contact : {{contact.cn}}</h3>
    <hr>
    <p>
        Vous etes sur le point de supprimer le contact <strong>{{contact.cn}}</strong>
        <dl class="dl-horizontal">
            {%if contact.telephone_number %}
            <dt data-toggle="tooltip" title="Téléphone principal"><i class="fa fa-phone fa-2x"></i></dt>
            <dd>
                {{contact.telephone_number}} {%if contact.phone_number_raccourci%}  - {{contact.phone_number_raccourci}}{%endif%}
            </dd>
            {% endif %}
            {%if contact.mobile %}
            <dt data-toggle="tooltip" title="Téléphone secondaire"><i class="fa fa-mobile fa-2x"></i></dt>
            <dd>
                {{contact.mobile}} {%if contact.phone_mobile_raccourci%} {{contact.phone_mobile_raccourci}}{%endif%}
            </dd>
            {% endif %}
             {%if contact.mail %}
            <dt data-toggle="tooltip" title="Téléphone secondaire"><i class="fa fa-envelope fa-2x"></i></dt>
            <dd>
                {{contact.mail}} {%if contact.phone_mobile_raccourci%} <{{contact.phone_mobile_raccourci}}>{%endif%}
            </dd>
            {% endif %}
        </dl>
    </p>
    <div class="alert alert-danger">
        <strong>Attention ! </strong><br>
        Cette action est irevessible, il ne vous sera pas possible de récuperer ce contact une fois la supression validé. <br>
        Pour rappel depuis l'interface <a href="https://client.voxity.fr/" target="_blank">client.voxity.fr</a> il vous est possible d'exporter l'ensemble de votre annuaire sous format CSV.
    </div>
    <form action="" method="POST" class="text-center">
        <input type="hidden" name="uid" value="{{contact.uid}}">
        <button type="submit" class="btn btn-danger">Supprimer <i class="fa fa-trash-o"></i></button>
    </form>
</div>
{% endblock %}

app/controllers/contacts/templates/contacts/view.html
{% extends "layout.html" %}
{% block body %}
    <h3>Détail du contact</h3>
    <hr>
    <div class="col-xs-12">
        <table class="table table-hover">
            <tr>
                <td class="text-center minimal"><i class="fa fa-user"></i></td>
                <td class="text-right"><strong>Nom</strong></td>
                <td colspan="2">{{contact.cn}}</td>
            </tr>
            <tr>
                <td class="text-center minimal"><i class="fa fa-phone"></i></td>
                <td class="text-right "><strong>Téléphone principal</strong></td>
                {%set val = contact.telephone_number|val_or_label("N/A") %}
                <td {%if val == contact.telephone_number%}class="callable"{%endif%}>{{val}}</td>
                <td class="minimal">
                    {%if is_mobile(contact.telephone_number)%}
                    <a href="{{url_for('SMS.new', phone_number=contact.telephone_number)}}" class="btn btn-success"><i class="fa fa-comment-o"></i></a>
                    {%endif%}
                </td>
            </tr>
            <tr>
                <td class="text-center minimal"><i class="fa fa-keyboard-o"></i></td>
                <td class="text-right"><strong>raccourcie</strong> &nbsp; <i class="fa fa-angle-up"></i></td>
                <td colspan="2">{{contact.phone_number_raccourci|val_or_label("N/A")}}</td>
            </tr>
            <tr>
                <td class="text-center minimal"><i class="fa fa-phone"></i></td>
                <td class="text-right"><strong>Téléphone secondair</strong></td>
                {%set val = contact.mobile|val_or_label("N/A") %}
                <td {%if val == contact.mobile%}class="callable"{%endif%}>{{val}}</td>
                <td class="minimal">
                    {%if is_mobile(contact.mobile)%}
                    <a href="{{url_for('SMS.new', phone_number=contact.mobile)}}" class="btn btn-success"><i class="fa fa-comment-o"></i></a>
                    {%endif%}
                </td>
            </tr>
            <tr>
                <td class="text-center minimal"><i class="fa fa-keyboard-o"></i></td>
                <td class="text-right"><strong>raccourcie</strong> &nbsp; <i class="fa fa-angle-up"></i></td>
                <td colspan="2">{{contact.phone_mobile_raccourci|val_or_label("N/A")}}</td>
            </tr>
            <tr>
                <td class="text-center minimal"><i class="fa fa-envelope"></i></td>
                <td class="text-right"><strong>Adresse mail</strong></td>
                <td colspan="2">{{contact.mail|val_or_label("N/A")}}</td>
            </tr>
        </table>
        <hr>
        {% if not read_only and is_admin()%}
        <div class="btn-group btn-group-justified" role="group">
            <a href="{{url_for('CONTACT.edit', uid=contact.uid)}}" class="btn btn-info">
                <i class="fa fa-edit"></i>
                Modifier
            </a>
            <a href="{{url_for('CONTACT.remove_warning', uid=contact.uid)}}" class="btn btn-danger">
                <i class="fa fa-trash-o"></i>
                Supprimer
            </a>
        </div>
        {% endif %}
    </div>
{% endblock %}