app/controllers/account.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, session, abort, current_app, redirect, request, url_for
from flask.json import jsonify
from app.voxity import self_user, logout, bind, oauth_status, save_token, refresh_token
from app.controllers import is_auth, clear_session, valide_session


ACCOUNT = Blueprint('ACCOUNT', __name__)
LIST_AVAILABLE = [5, 10, 25, 50, 100]


def refresh_user_session():
    try:
        session['user'] = self_user()
    except Exception:
        abort(500)


@ACCOUNT.route('me.json', methods=["GET"])
@is_auth
def me():
    refresh_user_session()
    return jsonify({'data': self_user()})


@ACCOUNT.route('me.html', methods=["GET"])
@is_auth
def me_view():
    refresh_user_session()
    return render_template('account/me.html')


@ACCOUNT.route('settings/notify.html', methods=["GET"])
def settings_notify():
    refresh_user_session()
    return render_template(
        'account/notify.html',
        container_class='container-fluid'
    )


@ACCOUNT.route('status.json', methods=["GET"])
def get_oauth_status():
    return jsonify({'data': oauth_status()})


@ACCOUNT.route('logout', methods=["GET"])
def logout_me():
    try:
        logout()
    except Exception:
        pass
    clear_session()
    return redirect(url_for('PUBLIC.index'))


@ACCOUNT.route('signin-check', methods=["GET"])
def signin_check(try_refresh=True):
    if valide_session():
        oauth_s = oauth_status()
        if oauth_s is not None and oauth_s == 'authenticated':
            return redirect(request.args.get('next', url_for('DEVICES.devices_view')))
        elif oauth_s is None and try_refresh:
            refresh_token()
            return signin_check(try_refresh=False)
        else:
            return redirect(url_for('ACCOUNT.signin'))
    else:
        return redirect(url_for('ACCOUNT.signin'))


@ACCOUNT.route('signin', methods=["GET"])
def signin():
    clear_session()

    if request.args.get('next', False):
        session['next_uri_aft_signin'] = request.args['next']
        session.modified = True

    voxity_bind = bind(redirect_uri=current_app.config['REDIRECT_URI'])
    authorization_url, state = voxity_bind.authorization_url(
        current_app.config['AUTHORIZATION_BASE_URL']
    )
    session['authorization_url'] = authorization_url
    return redirect(authorization_url)


@ACCOUNT.route("signin-callback", methods=["GET"])
def callback():
    """
    Step 3: Retrieving an access token.
    The user has been redirected back from the provider to your registered
    callback URL. With this redirection comes an authorization code included
    in the redirect URL. We will use that to obtain an access token.
    """

    voxity_bind = bind(
        redirect_uri=current_app.config['REDIRECT_URI']
    )
    save_token(voxity_bind.fetch_token(
        current_app.config['TOKEN_URL'],
        client_secret=current_app.config['CLIENT_SECRET'],
        authorization_response=request.url
    ))
    if 'next_uri_aft_signin' in session:
        return redirect(session.pop('next_uri_aft_signin'))
    else:
        return redirect(url_for('DEVICES.devices_view'))

app/controllers/contacts.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, request, abort, redirect, url_for, session
from flask.json import jsonify
from app.voxity import contact
from app.controllers import is_auth, is_admin
from app.utils import value_or_zero
from app.voxity.objects.contact import ContactForm


CONTACT = Blueprint('CONTACT', __name__)
LIST_AVAILABLE = [5, 10, 25, 50, 100]


@CONTACT.route('all.json', methods=["GET"])
@is_auth
def json_data():
    resp = contact.get().get('list', [])
    for num in contact.Contact.LOCAL_EXTEN.keys():
        resp.append({
            'telephoneNumber': num,
            'cn': contact.Contact.LOCAL_EXTEN[num]
        })
    return jsonify({'data': resp})


@CONTACT.route('', methods=["GET"])
@CONTACT.route('index.html', methods=["GET"])
@is_auth
def view():

    item = request.args.get('item', 25)
    page = request.args.get('page', 1)
    pager = dict()

    if item != 'all':
        contacts = contact.get(page=page, limit=item, ret_object=True)
        contact_total = int(value_or_zero(contacts['pager']['total_item']))

        # try:
        item = int(item)
        pager['current'] = int(value_or_zero(contacts['pager']['curent']))
        pager['max'] = int(value_or_zero(contacts['pager']['max_page']))
        pager['min'] = 1
        pager['start'] = 1
        pager['end'] = pager['max']

        if pager['end'] - pager['start'] > 10:
            pager['start'] = pager['current'] - 5
            if pager['start'] < 1:
                pager['start'] = 1

            pager['end'] = pager['start'] + 10
            if pager['end'] > pager['max']:
                pager['end'] = pager['max']
                pager['start'] = pager['end'] - 10

        # except Exception:
            # contacts = contact.get(ret_object=True)
            # item = 'all'
    else:
        contacts = contact.get(ret_object=True)
        contact_total = contact['pager']
    return render_template(
        'contacts/index.html',
        container_class='container-fluid',
        contacts=contacts['list'],
        pager=pager,
        item=item,
        items=LIST_AVAILABLE,
        contact_total=contact_total,
        search_mode=False,
    ).encode('utf-8')


@CONTACT.route('<uid>.json', methods=["GET"])
@is_auth
def contact_uid(uid=None):
    c = contact.get_uid(uid=uid)
    if c:
        return jsonify({'data': c})
    else:
        abort(404)


@CONTACT.route('search.html', methods=['GET'])
@is_auth
def search():
    c = list()
    form_value = dict()
    if not request.args.get('name', None):
        abort(400)
    else:
        form_value['name'] = "{0}".format(request.args.get('name', ''))

    c = contact.get(cn=form_value['name'], ret_object=True)
    return render_template(
        'contacts/index.html',
        container_class='container-fluid',
        contacts=c['list'],
        item="all",
        contact_total=len(c['list']),
        search_mode=True,
        form_value=form_value
    ).encode('utf-8')


@CONTACT.route('search.json', methods=['GET'])
@is_auth
def search_json():
    search = dict()
    for k in request.args:
        search[k] = request.args[k]

    c = contact.get(**search)
    return jsonify({'data': c})


@CONTACT.route('whois.json', methods=['GET'])
@is_auth
def whois():

    if not request.args.get('number', ''):
        abort(400)

    c = list()
    name_list = list()

    number = '{0}'.format(
        request.args.get('number')
    ).replace(' ', '').replace('.', '').replace('-', '')

    if number in contact.Contact.LOCAL_EXTEN:
        c.append({
            'telephoneNumber': number,
            'cn': contact.Contact.LOCAL_EXTEN[number]
        })
    else:
        c += contact.get()['list']

    for elt in c:
        if elt.get('mobile', '') == number or \
           elt.get('telephoneNumber', '') == number:
            name_list.append(elt)

    return jsonify({'data': name_list})


@CONTACT.route('whois.html', methods=['GET'])
@is_auth
def whois_view():

    if not request.args.get('number', ''):
        abort(400)

    c = list()
    name_list = list()

    number = '{0}'.format(
        request.args.get('number')
    ).replace(' ', '').replace('.', '').replace('-', '')

    if number in contact.Contact.LOCAL_EXTEN:
        c.append(
            contact.Contact(
                uid='local-' + number,
                telephoneNumber=number,
                cn=contact.Contact.LOCAL_EXTEN[number]
            )
        )
    else:
        c += contact.get(ret_object=True)['list']

    for elt in c:
        if elt.mobile == number or \
           elt.telephone_number == number:
            name_list.append(elt)

    if len(name_list) == 1:
        return redirect(url_for('.view_uid', uid=name_list[0].uid))
    else:
        return render_template(
            'contacts/index.html',
            container_class='container-fluid',
            contacts=name_list,
            item="all",
            contact_total=len(name_list),
            whois_mode=True
        ).encode('utf-8')


@CONTACT.route('add.html', methods=['GET'])
@is_auth
@is_admin
def get_add(form=None, api_errors=None):
    validate_state = False
    if form:
        validate_state = True
    return render_template(
        'contacts/form.html',
        form=form or ContactForm(),
        api_errors=api_errors,
        validate_state=validate_state
    ).encode('utf-8')


@CONTACT.route('add.html', methods=['POST'])
@is_auth
@is_admin
def post_add():
    api_errors = None
    form = ContactForm(request.form)
    form.strip_value()
    if form.validate():
        c = form.get_object(contact.Contact)
        resp = contact.add(**c.to_dict(is_query=True))
        if resp.get('status', False) == 200 and resp.get('result', {}).get('uid', False):
            session['new_contact'] = c.to_dict()
            return redirect(url_for('.view'))
        else:
            api_errors = resp.get('error', {'internal': 'Error inconnue'})
            if not isinstance(api_errors, dict):
                api_errors = {'message': api_errors}

    return get_add(form=form, api_errors=api_errors)


@CONTACT.route('local-<num>.html', methods=["GET"])
@is_auth
def view_local(num):
    c = contact.Contact(
        uid='local-' + num,
        telephoneNumber=num,
        cn=contact.Contact.LOCAL_EXTEN[num]
    )

    return render_template(
        'contacts/view.html',
        contact=c,
        read_only=True
    ).encode('utf-8')


@CONTACT.route('<uid>.html', methods=["GET"])
@is_auth
def view_uid(uid):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    return render_template(
        'contacts/view.html',
        contact=c,
    ).encode('utf-8')


@CONTACT.route('edit/<uid>.html', methods=["GET"])
@is_auth
@is_admin
def edit(uid=None):
    c = contact.get_uid(uid=uid, ret_object=True)
    if c:
        c_form = ContactForm(**c.to_dict())
        return render_template(
            'contacts/form.html',
            form=c_form,
            edit_mode=True
        ).encode('utf-8')
    else:
        abort(404)


@CONTACT.route('edit/<uid>.html', methods=["POST"])
@is_auth
@is_admin
def edit_save(uid=None):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    if request.form['uid'] != uid:
        abort(400)

    c_form = ContactForm(request.form)
    c_form.strip_value()
    if c_form.validate():
        c = c_form.get_object(contact.Contact)
        resp = contact.update(**c.to_dict(is_query=True))
        if resp and resp.get('result') and resp.get('result').get('uid', None) == uid and not resp.get('errors') and not resp.get('error'):
            session['update_contact'] = c.to_dict()
            return redirect(url_for('.view'))
        else:
            error = resp.get('error', {})
            if not isinstance(error, dict):
                error = {
                    'message': error
                }
            return render_template(
                'contacts/form.html',
                form=c_form,
                edit_mode=True,
                api_errors=error,
                validate_state=True
            ).encode('utf-8')
    else:
        return render_template(
            'contacts/form.html',
            form=c_form,
            edit_mode=True,
            validate_state=True
        ).encode('utf-8')


@CONTACT.route('remove-<uid>.html', methods=["GET"])
@is_auth
@is_admin
def remove_warning(uid):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    return render_template(
        'contacts/remove.html',
        contact=c
    ).encode('utf-8')


@CONTACT.route('remove-<uid>.html', methods=["POST"])
@is_auth
@is_admin
def remove(uid):
    c = contact.get_uid(uid=uid, ret_object=True)
    if not c:
        abort(404)

    if request.form['uid'] != uid:
        abort(400)

    if contact.remove(uid):
        session['remove_contact'] = c.to_dict()
        return redirect(url_for('.view'))
    else:
        abort(500)

app/controllers/devices/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals
from flask import Blueprint, render_template, abort
from flask.json import jsonify
from app.voxity import device, channel
from app.controllers import is_auth
from app.utils import roundup


DEVICES = Blueprint('DEVICES',
    __name__,
    template_folder='templates',
    url_prefix='/devices',
    static_folder='static'
)


@DEVICES.route('/index.html', methods=["GET"])
@is_auth
def index():
    item_per_lst = 4
    devices = device.get(ret_object=True, sort_by_extention=True)
    total_devices = len(devices)
    col = roundup(total_devices / item_per_lst)
    if col >= 4:
        item_per_lst = roundup(total_devices / 3)
        col = 3

    if col == 1:
        container_class = 'container'
    else:
        container_class = 'container-fluid'

    return render_template(
        'devices/index.html',
        container_class=container_class,
        col_length=col,
        item_per_lst=item_per_lst,
        devices=devices
    )


@DEVICES.route('/index.json', methods=["GET"])
@is_auth
def devices_json():
    return jsonify({'data': device.get()})


@DEVICES.route('/<device_id>.html', methods=["GET"])
@is_auth
def device_view(device_id=None):
    d = device.get_id(device_id, ret_object=True)

    return render_template(
        'devices/id.html',
        container_class='container-fluid',
        device=d,
        calls=channel.get_local_filter(ret_object=True, exten=d.extension)
    )


@DEVICES.route('/<device_id>.json', methods=["GET"])
@is_auth
def device_json(device_id):

    return jsonify({'data': device.get_id(device_id, ret_object=False)})


@DEVICES.route('/<device_id>/channels.json', methods=["GET"])
def device_channels_json(device_id):
    d = device.get_id(device_id, ret_object=True)
    if d:
        return jsonify({'data': channel.get_local_filter(ret_object=False, exten=d.extension)})
    else:
        abort(404)

app/templates/_macro.html
{% macro input_text(field, success='', errors='', show_label=1, addon_icon='', placeholder='', error_list='', validate='') %}
{%if not show_label and not placeholder[0]%}
    {% set placeholder = field.label.text%}
{%endif%}
{%if errors%}
    {% set class_form_group = 'has-error'%}
{%elif success%}
    {% set class_form_group = 'has-success'%}
{%else%}
    {% set class_form_group = ''%}
{%endif%}
{%if validate and field.data and not errors%}
    {% set class_form_group = 'has-success'%}
{%endif%}
<div class="form-group {{class_form_group}}">
    {%if show_label%}{{field.label(class="control-label")}}{%endif%}
    {%if addon_icon%}
    <div class="input-group">
        <span class="input-group-addon"><i class="{{addon_icon}}"></i></span>
        {{field(class="form-control", placeholder=placeholder)}}
    </div>
    {%else%}{{field(class="form-control", placeholder=placeholder)}}{%endif%}
    {%if errors%}
    <span class="help-block small text-danger">
        <ul>{%for e in errors%}
            <li>{{e}}</li>
        {%endfor%}</ul>
    </span>
    {%endif%}
</div>
{% endmacro %}

{% macro input_text_button(field, success='', errors='', show_label=1, addon_icon='', placeholder='', error_list='', validate='', btn_content='OK', btn_attr='')%}
{%if not show_label and not placeholder[0]%}
    {% set placeholder = field.label.text%}
{%endif%}
{%if errors%}
    {% set class_form_group = 'has-error'%}
{%elif success%}
    {% set class_form_group = 'has-success'%}
{%else%}
    {% set class_form_group = ''%}
{%endif%}
{%if validate and field.data and not errors%}
    {% set class_form_group = 'has-success'%}
{%endif%}
<div class="form-group {{class_form_group}}">
    {%if show_label%}{{field.label(class="control-label")}}{%endif%}
    <div class="input-group">
        <span class="input-group-addon"><i class="{{addon_icon}}"></i></span>
        {{field(class="form-control", placeholder=placeholder)}}
        <span class="input-group-btn">
            <button class="btn btn-default" type="button" {{btn_attr|safe}}>{{btn_content|safe}}</button>
        </span>
      </span>
    </div>
    {%if errors%}
    <span class="help-block small text-danger">
        <ul>{%for e in errors%}
            <li>{{e}}</li>
        {%endfor%}</ul>
    </span>
    {%endif%}
</div>
{% endmacro %}

{% macro nav_link(name, bp_endpoint, icon_class, li_class) %}
<li class="{{li_class}}{% if bp_endpoint != '#' and url_for(bp_endpoint) == request.path %} active{% endif %}">
    <a href="{%if bp_endpoint != '#' %}{{url_for(bp_endpoint)}}{%else%}#{%endif%}">
        <i class="{{icon_class}} fa-fw"></i> 
         <span class="hidden-sm hidden-xs">{{name}}</span>
    </a>
</li>
{% endmacro %}

app/templates/footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-5">
                <a href="{{config['ABOUT_URI']}}">
                Proposé par Cedric TC
                </a>
            </div>
            <div class="col-xs-2 text-center">
                <a href="{{config['INDEX_PAGE_URI']}}">
                    <img src="{{url_for('static', filename='icon/app/75-icon_app.png')}}" alt="" class="img img-logo-app">
                </a>
            </div>
            <div class="col-xs-5 text-right">
                <a href="{{config['CHANGELOG_URI']}}">
                    Version {{config['__VERSION__']}}
                </a>
            </div>
        </div>
    </div>
</footer>

app/templates/layout.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="THIVOLLE-CAZAT Cédric">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>vox-ui-api</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="{{url_for('static', filename='res/bootstrap/dist/css/bootstrap.min.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='res/toastr/toastr.min.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='res/font-awesome/css/font-awesome.min.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link rel="apple-touch-icon" href="{{url_for('static', filename='icon/app/75-icon_app.png')}}"> 
        <link rel="icon" href="{{url_for('static', filename='icon/fav/vox-ui-api.ico')}}">
        {% block css %}{% endblock %}

    </head>
    <body>
{%if config['TRACKER_FILE']%}{% include config['TRACKER_FILE'] %}{%endif%}
{% from '_macro.html' import input_text, input_text_button with context %}
        <div class="header clearfix">
            <h3 class="text-muted">
                <img src="{{url_for('static', filename='icon/fav/75-vox-ui-api.png')}}" alt="" class="img img-logo">
                <span class="hidden-xs">Vox-ui-api</span>
                <sup class="small" data-toggle="tooltip" title="{{config['__VERSION__']}}eta" data-placement="bottom">
                    <span class="label label-danger" style="font-weight: 200;">&beta;</span>
                </sup>

                <div class="dropdown pull-right">
                    {%if 'user' in session%}
                    <button class="btn btn-default dropdown-toggle" type="button" id="dd-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <span data-toggle="tooltip" data-placement="bottom" title="{{session['user']['internalExtension']}}">{{session['user']['name']}}</span> 
                        <span class="fa-stack">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-user fa-stack-1x"></i>
                        </span>
                        <i class="fa fa-angle-down"></i>
                    </button>
                  <ul class="dropdown-menu" aria-labelledby="dd-user">
                    <li {% if url_for('ACCOUNT.me_view') == request.path %}class="active"{% endif %}><a href="{{url_for('ACCOUNT.me_view')}}">
                        <i class="fa fa-user fa-fw"></i> Comptes
                    </a></li>
                    <li {% if url_for('ACCOUNT.settings_notify') == request.path %}class="active"{% endif %}><a href="{{url_for('ACCOUNT.settings_notify')}}">
                        <i class="fa fa-cogs fa-fw"></i> Paramètres
                    </a></li>
                    <li role="separator" class="divider"></li>
                    {#<li><a href="{{url_for('ACCOUNT.logout_me')}}">
                        <i class="fa fa-power-off text-danger fa-fw"></i> Déconnexion
                    </a></li>#}
                    <li><a href="https://api.voxity.fr/api/v1/login" target="_BLANK">
                        <i class="fa fa-power-off text-danger fa-fw"></i> Déconnexion
                    </a></li>
                  </ul>
                  {% else %}
                    <a href="{{url_for('ACCOUNT.signin')}}" class="btn btn-default">Signin <i class="fa fa-sign-in"></i></a>
                  {%endif%}
                </div>
            </h3>
            <nav>
                <ul class="nav nav-pills pull-left">
                    <li role="presentation" {% if '/'.join((url_for('CONTACT.view').split('/')[0:-1])) in request.path %}class="active"{% endif %}>
                        <a href="{{url_for('CONTACT.view')}}">
                            <i class="fa fa-book"></i>
                            <span class="hidden-sm hidden-xs">Contacts</span>
                        </a>
                    </li>
                    <li role="presentation" {% if url_for('DEVICES.index').split('/')[1] in request.path %}class="active"{% endif %}>
                        <a href="{{url_for('DEVICES.index')}}">
                            <i class="fa fa-dashboard"></i>
                            <span class="hidden-sm hidden-xs">Tableau de bord</span>
                        </a>
                    </li>
                    <li data-toggle="modal" data-target="#callModal" id="btn-callModal"><a href="#"><i class="fa fa-phone"></i></a></li>
                </ul>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation"><a href="https://voxity.fr" target="_blank" data-toggle="tooltip" title="Voxity" data-placement="bottom">
                        <!-- Voxity -->
                        <img class="img-vox-logo" src="{{url_for('static', filename='img/voxity-logo-75.png')}}" alt="voxity-logo">
                    </a></li>
                    <li role="presentation"><a href="https://api.voxity.fr/doc" target="_blank">API</a></li>
                    <li role="presentation"><a href="https://github.com/thivolle-cazat-cedric/vox-ui-api" target="_blank"><span class="fa fa fa-github-square"></span></a></li>
                </ul>
            </nav>
            
        </div>
        <div class="{{container_class or "container"}}">
            <div class="row">
                {% block body %}{% endblock %}
            </div>
        </div> <!-- /.container -->

        {% include 'footer.html'%}

        {% if 'oauth_token' in session and 'access_token' in session['oauth_token']%}
        <!-- callModal -->
        <div class="modal fade" id="callModal" tabindex="-1" role="dialog" aria-labelledby="callModalLabel">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="callModalLabel">Dialler</h4>
                    </div>
                    <div class="modal-body">
                        <form action="">
                            <div class="input-group">
                                <input type="tel" class="form-control" placeholder="Numéro de téléphone" aria-describedby="tel-number" id="telValue" autofocus>
                                <span class="input-group-btn">
                                    <button class="btn btn-success" type="submit"><span class="fa fa-chevron-right"></span></button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /callModal -->
        {%endif%}
        <script src="{{url_for('static', filename='res/jquery/dist/jquery.min.js')}}"></script>
        <script src="{{url_for('static', filename='res/bootstrap/dist/js/bootstrap.min.js')}}"></script>
        <!-- toastr -->
        <script src="{{url_for('static', filename='res/toastr/toastr.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/main.js')}}"></script>
        {% if 'oauth_token' in session and 'access_token' in session['oauth_token']%}
            <script src="{{url_for('static', filename='res/socket.io-client/dist/socket.io.min.js')}}"></script>
            <script type="text/javascript">
                var token = "{{session['oauth_token']['access_token']}}";
                var myExtension = "{{session['user']['internalExtension']}}";
                var DASHBOARD_URI = "{{url_for('DEVICES.index')}}";
            </script>
            <script src="{{url_for('static', filename='js/events.js')}}"></script>
        {%endif%}
        {% block jsscript %}{% endblock %}

    </body>


</html>